import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

function generateInvoiceNumber(): string {
  const prefix = "INV";
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `${prefix}-${timestamp}-${random}`;
}

export async function POST(request: Request) {
  try {
    const session = await auth();
    if (!session?.user || session.user.role === "TENANT") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { propertyId, month, year, dueDay } = await request.json();

    if (!propertyId || !month || !year) {
      return NextResponse.json(
        { error: "propertyId, month, and year are required" },
        { status: 400 }
      );
    }

    const property = await prisma.property.findFirst({
      where: { id: propertyId, landlordId: session.user.id },
      include: {
        units: {
          where: { status: "OCCUPIED" },
          include: {
            tenant: {
              where: { status: "ACTIVE" },
            },
          },
        },
      },
    });

    if (!property) {
      return NextResponse.json(
        { error: "Property not found" },
        { status: 404 }
      );
    }

    const dueDateDay = dueDay || 5;
    const dueDate = new Date(year, month - 1, dueDateDay);
    const invoices = [];

    for (const unit of property.units) {
      if (!unit.tenant) continue;

      const existing = await prisma.invoice.findFirst({
        where: {
          tenantId: unit.tenant.id,
          propertyId,
          isAutoGenerated: true,
          issueDate: {
            gte: new Date(year, month - 1, 1),
            lt: new Date(year, month, 1),
          },
        },
      });

      if (existing) continue;

      const invoice = await prisma.invoice.create({
        data: {
          invoiceNumber: generateInvoiceNumber(),
          tenantId: unit.tenant.id,
          propertyId,
          dueDate,
          status: "SENT",
          subtotal: unit.tenant.rentAmount,
          totalAmount: unit.tenant.rentAmount,
          isAutoGenerated: true,
          items: {
            create: {
              description: `Rent for ${new Date(year, month - 1).toLocaleString("default", { month: "long", year: "numeric" })}`,
              quantity: 1,
              unitPrice: unit.tenant.rentAmount,
              amount: unit.tenant.rentAmount,
              itemType: "RENT",
            },
          },
        },
        include: { items: true },
      });

      await prisma.notification.create({
        data: {
          userId: unit.tenant.userId,
          title: "New Invoice",
          message: `Your rent invoice ${invoice.invoiceNumber} for KES ${unit.tenant.rentAmount.toLocaleString()} is due ${dueDate.toLocaleDateString()}`,
          type: "INVOICE_SENT",
          invoiceId: invoice.id,
        },
      });

      invoices.push(invoice);
    }

    return NextResponse.json({
      message: `Generated ${invoices.length} invoice(s)`,
      invoices,
    });
  } catch (error) {
    console.error("Error auto-generating invoices:", error);
    return NextResponse.json(
      { error: "Failed to auto-generate invoices" },
      { status: 500 }
    );
  }
}
