"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
}

interface ReceiptData {
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  status: string;
  totalAmount: number;
  amountPaid: number;
  items: InvoiceItem[];
  tenantName: string;
  propertyName: string;
  unitNumber: string;
  mpesaReceiptNumber?: string;
  paidDate?: string;
}

export function DownloadReceiptButton({ data }: { data: ReceiptData }) {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    setLoading(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const { default: autoTable } = await import("jspdf-autotable");

      const doc = new jsPDF();

      // Header
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("LipaKodi", 14, 22);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("Payment Receipt", 14, 30);

      // Receipt info
      doc.setFontSize(10);
      doc.text(`Invoice: ${data.invoiceNumber}`, 14, 42);
      doc.text(`Issue Date: ${data.issueDate}`, 14, 48);
      doc.text(`Due Date: ${data.dueDate}`, 14, 54);
      doc.text(`Status: ${data.status}`, 14, 60);

      // Tenant / Property info
      doc.text(`Tenant: ${data.tenantName}`, 120, 42);
      doc.text(`Property: ${data.propertyName}`, 120, 48);
      doc.text(`Unit: ${data.unitNumber}`, 120, 54);

      if (data.mpesaReceiptNumber) {
        doc.text(`M-Pesa Receipt: ${data.mpesaReceiptNumber}`, 120, 60);
      }
      if (data.paidDate) {
        doc.text(`Paid Date: ${data.paidDate}`, 120, 66);
      }

      // Items table
      const tableData = data.items.map((item) => [
        item.description,
        item.quantity.toString(),
        `KES ${item.unitPrice.toLocaleString()}`,
        `KES ${item.amount.toLocaleString()}`,
      ]);

      autoTable(doc, {
        startY: 74,
        head: [["Description", "Qty", "Unit Price", "Amount"]],
        body: tableData,
        theme: "striped",
        headStyles: { fillColor: [59, 130, 246] },
      });

      // Totals
      const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
      doc.setFont("helvetica", "bold");
      doc.text(`Total: KES ${data.totalAmount.toLocaleString()}`, 140, finalY);
      doc.text(
        `Paid: KES ${data.amountPaid.toLocaleString()}`,
        140,
        finalY + 6
      );
      const outstanding = data.totalAmount - data.amountPaid;
      if (outstanding > 0) {
        doc.setTextColor(220, 38, 38);
        doc.text(
          `Outstanding: KES ${outstanding.toLocaleString()}`,
          140,
          finalY + 12
        );
        doc.setTextColor(0, 0, 0);
      }

      // Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(
        "Generated by LipaKodi - Rental Management System",
        14,
        doc.internal.pageSize.height - 10
      );

      doc.save(`receipt-${data.invoiceNumber}.pdf`);
    } catch (error) {
      console.error("Failed to generate PDF:", error);
    }
    setLoading(false);
  }

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleDownload}
      disabled={loading}
    >
      <Download className="mr-2 h-4 w-4" />
      {loading ? "Generating..." : "Receipt"}
    </Button>
  );
}
